name: go

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/go.yaml
      - pkg/**
      - go.*
    tags:
      - v*
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/go.yaml
      - pkg/**
      - go.*
permissions:
  pull-requests: write

 
jobs:
  check:
    uses: int128/go-workflows/.github/workflows/check.yaml@v0.3.0
    with:
        go-version: 1.22.3
        golangci-lint-version: v1.58.2


  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.3
      - run: go test -v -race ./...

  workflow-telemetry-action:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
